#!/usr/bin/env bash
set -e

echo "postBuild: installing models and data"

python -m spacy download en_core_web_sm

python - <<'PY'
import nltk
nltk.download('vader_lexicon')
nltk.download('punkt')
nltk.download('stopwords')
PY

echo "postBuild complete."
